### ISSUE TITLE
실행하려는데 막 오류가 터집니다 ㅠㅜ

### ISSUE THREAD

**Issue by gwanwoo11** [SaidBySolo/Hiyobi-Downloder#3]
한번에 다운받을수를 입력해주세요(보통 1~5추천,cg집같은경우는 알아서 맞추세요.)
10
다운은 1번 검색은 2번을 입력해주세요
2
리스트검색은 1번, 제목,태그검색은 2번을 입력해주세요
1
리스트검색입니다. 몇번쨰 페이지를 검색할까요?
1
Traceback (most recent call last):
  File "/opt/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/opt/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
  File "/opt/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    idlist = loop.run_until_complete(search.hiyobilist(num=num))
  File "/opt/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
  File "/tmp/home/root/Hiyobot/src/search.py", line 5, in hiyobilist
    async with cs.get(f'https://api.hiyobi.me/list/{num}') as r:
  File "/opt/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/opt/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/opt/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/opt/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/opt/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.hiyobi.me:443 ssl:default [None]

공유기에 엔트웨어를 설치해서 거기에 설치하려했는데 실행하더니 오류를 내면서 뿜어버립니다ㅠㅠ 어떻게 해야하나요

**Comment by gwanwoo11** [comment]
그 전에 이부분에서도 에러가 떴었습니다

@RT-AX56U-3288:/tmp/home/root/Hiyobot# pip install -r requirements.txt
Requirement already satisfied: aiohttp[speedups] in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: aiofiles in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.5.0)
Requirement already satisfied: multidict<5.0,>=4.5 in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from aiohttp[speedups]->-r requirements.txt (line 1)) (4.7.6)
Requirement already satisfied: yarl<2.0,>=1.0 in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from aiohttp[speedups]->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from aiohttp[speedups]->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: chardet<4.0,>=2.0 in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from aiohttp[speedups]->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in /tmp/mnt/sda1/entware/lib/python3.8/site-packages (from aiohttp[speedups]->-r requirements.txt (line 1)) (19.3.0)
Collecting cchardet; extra == "speedups"
  Using cached cchardet-2.1.6.tar.gz (653 kB)
Collecting aiodns; extra == "speedups"
  Using cached aiodns-2.0.0-py2.py3-none-any.whl (4.8 kB)
Collecting brotlipy; extra == "speedups"
  Using cached brotlipy-0.7.0.tar.gz (413 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/mnt/sda1/entware/tmp/pip-install-d5bv_l7c/brotlipy/setup.py'"'"'; __file__='"'"'/tmp/mnt/sda1/entware/tmp/pip-install-d5bv_l7c/brotlipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/mnt/sda1/entware/tmp/pip-pip-egg-info-obzlc1jq
         cwd: /tmp/mnt/sda1/entware/tmp/pip-install-d5bv_l7c/brotlipy/
    Complete output (92 lines):
    c/_cffi_backend.c: In function 'b_callback':
    c/_cffi_backend.c:6245:5: warning: 'ffi_prep_closure' is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
         if (ffi_prep_closure(closure, &cif_descr->cif,
         ^~
    In file included from c/_cffi_backend.c:15:0:
    /opt/include/ffi.h:334:1: note: declared here
     ffi_prep_closure (ffi_closure*,
     ^~~~~~~~~~~~~~~~
    /opt/bin/ld: cannot find -lffi
    collect2: error: ld returned 1 exit status
    Traceback (most recent call last):
      File "/opt/lib/python3.8/distutils/unixccompiler.py", line 204, in link
      File "/opt/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
      File "/opt/lib/python3.8/distutils/spawn.py", line 36, in spawn
      File "/opt/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/lib/python3.8/distutils/core.py", line 148, in setup
      File "/opt/lib/python3.8/distutils/dist.py", line 966, in run_commands
      File "/opt/lib/python3.8/distutils/dist.py", line 985, in run_command
      File "/opt/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
      File "/opt/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
      File "/opt/lib/python3.8/distutils/cmd.py", line 313, in run_command
      File "/opt/lib/python3.8/distutils/dist.py", line 985, in run_command
      File "/opt/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
      File "/opt/lib/python3.8/distutils/command/install_lib.py", line 107, in build
      File "/opt/lib/python3.8/distutils/cmd.py", line 313, in run_command
      File "/opt/lib/python3.8/distutils/dist.py", line 985, in run_command
      File "/opt/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      File "/opt/lib/python3.8/distutils/command/build_ext.py", line 343, in run
      File "/opt/lib/python3.8/distutils/command/build_ext.py", line 452, in build_extensions
      File "/opt/lib/python3.8/distutils/command/build_ext.py", line 477, in _build_extensions_serial
      File "/opt/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
      File "/opt/lib/python3.8/distutils/command/build_ext.py", line 553, in build_extension
      File "/opt/lib/python3.8/distutils/ccompiler.py", line 713, in link_shared_object
      File "/opt/lib/python3.8/distutils/unixccompiler.py", line 206, in link
    distutils.errors.LinkError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
      File "/opt/tmp/easy_install-ngd6e3e6/cffi-1.14.0/setup.py", line 186, in <module>
      File "/opt/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      File "/opt/lib/python3.8/distutils/core.py", line 163, in setup
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
      File "/opt/lib/python3.8/contextlib.py", line 131, in __exit__
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
      File "/opt/lib/python3.8/contextlib.py", line 131, in __exit__
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
      File "/opt/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
      File "/opt/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
      File "/opt/tmp/easy_install-ngd6e3e6/cffi-1.14.0/setup.py", line 186, in <module>
      File "/opt/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      File "/opt/lib/python3.8/distutils/core.py", line 163, in setup
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/mnt/sda1/entware/tmp/pip-install-d5bv_l7c/brotlipy/setup.py", line 9, in <module>
        setup(
      File "/opt/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
      File "/opt/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
      File "/opt/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
      File "/opt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
      File "/opt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
      File "/opt/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
      File "/opt/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
      File "/opt/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
      File "/opt/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
      File "/opt/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
      File "/opt/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
      File "/opt/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
@RT-AX56U-3288:/tmp/home/root/Hiyobot#

**Comment by SaidBySolo** [comment]
사용하시는 ISP가 어떻게되시나요

**Comment by designed-re** [comment]
-> pip install 오류 참고: https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation

P.S. KT통신사를 제외한 SKT,LG는 API, CDN주소도 검열당하십니다. GoodBYEDPI 또는 우회를 사용해보세요
